services:
  backend:
    build:
      context: .
      dockerfile: server/dockerfile
    ports:
      - "8000:8000"
    env_file: .env.docker

  frontend:
    build:
      context: .
      dockerfile: client/dockerfile
    ports:
      - "5000:5000"
    env_file: .env.docker
