services:
  backend:
    build:
      context: .
      dockerfile: server/dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - /home/ftpDev/vxacademy/uploads:/app/server/uploads
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: client/dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5000:5000"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    restart: unless-stopped
